### ISSUE TITLE
Getting some error

### ISSUE THREAD

**Issue by Shell2548-Sh** [asidsx/EasyTranslateCraftopia#1]
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/133001a3-89f8-469c-bb78-e99f1c9f37a6)
`Файл успешно исправлен и сохранен.`
`Exception in Tkinter callback`
`Traceback (most recent call last):`
`  File "tkinter\__init__.py", line 1921, in __call__`
`  File "wind.py", line 42, in load_jp`
`    self.load_lang()`
`  File "wind.py", line 198, in load_lang`
`  File "json\__init__.py", line 293, in load`
`  File "json\__init__.py", line 346, in loads`
`  File "json\decoder.py", line 340, in decode`
`json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 3)`
how can i fix.

**Comment by asidsx** [comment]
You have errors in the file old.txt. This file is in JSON format, maybe you forgot to remove a comma at the end of the last line, or vice versa, removed it somewhere in the middle. I recommend trying Notepad++ with the jstool plugin -> JSON Sort. This can fix most errors. In general, it's a good practice to perform this kind of sorting after translations and working with these files.
And check file(old.txt) here
json.decoder.JSONDecodeError: **_Extra data_**: **line 2 column 1 (char 3)**
And in JSON format, you cannot use Tab characters, only spaces.

**Comment by Shell2548-Sh** [comment]
Thank for your reply.
I tried to use jstool plugin and already JSON Sorted.
Also test with old.txt there's a few line like this. (No tab character, only spaces)

`{`
`    "000_Keyword/ATK": "ATK",`
`    "000_Keyword/CRITICAL_DMG_MAGICAL": "Magical Critical Damage",`
`    "000_Keyword/CRITICAL_DMG_PHYSICAL": "Physical Critical Damage"`
`}`

But still getting same error [ json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 3) ]

**Comment by asidsx** [comment]
I just checked, and I don't have any errors. The file has been changed. Maybe you inserted the wrong dump?

{
  "000_Keyword/ATK": "ATK",
  "000_Keyword/ATK_RATE": "ATK ^",
  "000_Keyword/CRITICAL_DMG": "クリティカルダメージ ^",
  "000_Keyword/CRITICAL_DMG_MAGICAL": "Magical Critical Damage",
  "000_Keyword/CRITICAL_DMG_PHYSICAL": "Physical Critical Damage",
  "000_Keyword/CRITICAL_PROB": "クリティカル率 ^",
  "000_Keyword/CRITICAL_PROB_MAGICAL": "魔法クリティカル率 ^",
  "000_Keyword/CRITICAL_PROB_PHYSICAL": "物理クリティカル率 ^",
  "000_Keyword/DEF": "DEF ^",
  "000_Keyword/DEF_RATE": "DEF ^",
  
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/106923482/b7b8f2c7-142c-41ed-80e1-15a90934aecc)
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/106923482/f7dc458d-22c1-4f48-9aae-9a008d2754e5)

**Export Dump**

![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/106923482/52f3dd9e-d2e6-44c2-86ac-8c4c82c0ea1e)

**Comment by Shell2548-Sh** [comment]
Yeah, The Dump is same.
Can you give me that whole file that you think it's work.
Maybe should i put whole file to you?
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/0bb795cc-c06f-45df-ab69-29b425a24f27)

**Comment by asidsx** [comment]
I understand what the problem is. You didn't download the program, but you compiled it. If that's the case, then I forgot to update the code... I have already uploaded the latest version.

**Comment by asidsx** [comment]
and you can download my dump
[dump.rar](https://github.com/asidsx/EasyTranslateCraftopia/blob/main/dump.rar)

**Comment by Shell2548-Sh** [comment]
The latest version update getting this [ IndexError: list index out of range ]
What should i do now?
If you busy, You can reply to helping me later.

**Comment by asidsx** [comment]
I made a mistake again.
I re-uploaded the latest code.

**Comment by Shell2548-Sh** [comment]
What am i doing wrong? TwT
It the same as before.
**json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 3)**

It's wrong at my old.txt right?
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/55ef6665-5b27-4ad8-a80b-bfb83efede77)

**Comment by asidsx** [comment]
I have just installed Windows 11 on a virtual machine and checked it to ensure compatibility, and everything worked for me...
i create little file old
[old.txt](https://github.com/asidsx/EasyTranslateCraftopia/files/12617948/old.txt)
you can check him...

**Comment by asidsx** [comment]
Did you check the dependencies? Are they all installed?
import tkinter as tk
import re
import chardet
import json
import os
import subprocess
import codecs

Like this."

pip install chardet

**Comment by Shell2548-Sh** [comment]
Already installed.

**Comment by asidsx** [comment]
All incoming files must have the UTF-8 encoding.

**Comment by Shell2548-Sh** [comment]
How can i check?
Or just save overwrite it as UTF-8 encoding?

**Comment by asidsx** [comment]
Yes, you can forcefully change the encoding through Notepad++.

**Comment by Shell2548-Sh** [comment]
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/ce228ced-5359-4083-9083-80918a4f355a)
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/dae491aa-f96e-4e40-9fcb-bc919960b59c)

**Comment by asidsx** [comment]
Remove the old.txt file, it should simply generate the output2.txt file without it.

**Comment by Shell2548-Sh** [comment]
Yeah
Should it be only one line?
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/5c0e6bd8-602b-4d17-a3f6-20cded5d493c)

**Comment by asidsx** [comment]
I removed part of the code responsible for error checking, it doesn't complain anymore and everything is running smoothly.

**Comment by Shell2548-Sh** [comment]
TwT
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/df4ec409-a762-49fd-a310-9e6770335918)

**Comment by asidsx** [comment]
That's very strange. On another system, I downloaded the latest version of Python, compiled the file, and it worked for me. The only dependency I installed on plain Python was chardet.

**Comment by asidsx** [comment]
Do you compile using pyinstaller --onefile wind.py?

**Comment by Shell2548-Sh** [comment]
Just double-click run it...
Complie needed?

**Comment by asidsx** [comment]
no not needed
I have uploaded the latest version of the program, please redownload it.
https://github.com/asidsx/EasyTranslateCraftopia/releases/tag/RS-1.3

**Comment by Shell2548-Sh** [comment]
Downloaded, Then test?

**Comment by asidsx** [comment]
yes

**Comment by Shell2548-Sh** [comment]
old.txt already JSON Sorted.
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/d3e587c9-3a13-4207-9821-1dfe4f8f7a40)
Should i do all step at start? install python, pip install, etc..

**Comment by asidsx** [comment]
Could something be blocking the program? Try running it as an administrator.

**Comment by Shell2548-Sh** [comment]
Same
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/3f32dd61-6a2f-4b24-a543-fa30f4419f11)

**Comment by asidsx** [comment]
https://ufile.io/sol3lyph
Here, I uploaded what I tested it on.

**Comment by Shell2548-Sh** [comment]
Wait, it work fine
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/bf284f51-b21b-439c-add1-620a3accd58b)

wind.exe that you sent is bigger than i complie and it work
Now going test with my file.

**Comment by asidsx** [comment]
I compiled it on Windows 11, installed the latest version of Python, installed pyinstaller, and one dependency, chardet. Then, I compiled it using pyinstaller --onefile wind.py.

**Comment by Shell2548-Sh** [comment]
That you sent work fine.
Problem with my file it's not work.

**Comment by asidsx** [comment]
Send it to me, I will take a look at it.

**Comment by Shell2548-Sh** [comment]
My file [old.txt](https://github.com/asidsx/EasyTranslateCraftopia/files/12618646/old.txt)
I getting it from https://github.com/BudgieY/AdditionalLanguagesForCraftopia/tree/20230711.2120/plugins/lang en.json
Then JSON Sort.

**Comment by asidsx** [comment]
Everything is great for me, even without sorting, I launched it and everything is okay right away

**Comment by asidsx** [comment]
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/106923482/a4d22311-4623-4d9b-a031-f444831b53ab)

**Comment by Shell2548-Sh** [comment]
Can you test with this file? 
[th.txt](https://github.com/asidsx/EasyTranslateCraftopia/files/12618718/th.txt)
This's my file that translated from Eng to Thai.

**Comment by asidsx** [comment]
[data.txt](https://github.com/asidsx/EasyTranslateCraftopia/files/12618732/data.txt)

**Comment by Shell2548-Sh** [comment]
When i changed your Dump file to my folder, It's work fine
But with my Dump file will getting error [ json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 3) ]

**Comment by asidsx** [comment]
try it
https://easyupload.io/4mot7n

**Comment by Shell2548-Sh** [comment]
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/ec715274-6192-4550-8bf9-2c2391e22fae)
.Net Desktop runtime 5.0 right?

**Comment by asidsx** [comment]
yes it was old release of this program

**Comment by Shell2548-Sh** [comment]
What should i do?
Resource selected
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/0a3974a0-9129-4587-aa60-a080b77ec58a)

**Comment by asidsx** [comment]
The very last one.

**Comment by Shell2548-Sh** [comment]
Should i Export Raw or Export Dump? (Dump right? Okay)

**Comment by asidsx** [comment]
Export Dump

**Comment by Shell2548-Sh** [comment]
Alright it work now.
![image](https://github.com/asidsx/EasyTranslateCraftopia/assets/67862642/800f977b-5399-4c0b-98b8-fca755390187)

**Comment by asidsx** [comment]
I didn't expect everything to turn out like this, well, at least I made some adjustments to the code and fixed the UABEAvalonia version to the required one.

**Comment by asidsx** [comment]
For some reason, they changed the export structure.

**Comment by Shell2548-Sh** [comment]
I think it's python version problem lol
But now it work.
Sorry that am i wasting your time, Thank for your hard work.

**Comment by asidsx** [comment]
And thank you too, you found such a non-obvious problem...
